#ifndef SWND_VERSION_INCLUDED
#define SWND_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str)        MAKE_STR_HELPER(a_str)

#define LESA_VERSION_MAJOR 1
#define LESA_VERSION_MINOR 0
#define LESA_VERSION_PATCH 0
#define LESA_VERSION_BETA  1
#define LESA_VERSION_VERSTRING   \
    MAKE_STR(LESA_VERSION_MAJOR) \
    "." MAKE_STR(LESA_VERSION_MINOR) "." MAKE_STR(LESA_VERSION_PATCH) "." MAKE_STR(LESA_VERSION_BETA)

#endif
